<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="output\**" />
    <EmbeddedResource Remove="output\**" />
    <None Remove="output\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared-public\ConfigurationClassBuilder\ConfigurationClassBuilder.csproj" />
    <ProjectReference Include="..\..\..\..\shared-public\Core\CSharp\Core.csproj" />
    <ProjectReference Include="..\HVPSConstants\HVPSConstants.csproj" />
  </ItemGroup>

</Project>
